require("plugins.plugins_config.lualine")
require("plugins.plugins_config.telescope")
require("plugins.plugins_config.cargo")
require("plugins.plugins_config.floaterm")
require("plugins.plugins_config.json")
require("plugins.plugins_config.nerdcommenter")
require("plugins.plugins_config.nerdfont")
require("plugins.plugins_config.rust")
require("plugins.plugins_config.undotree")
require("plugins.plugins_config.visual-multi")
require("plugins.plugins_config.yaml-revealer")
require("plugins.plugins_config.coc")
require("plugins.plugins_config.treesitter")
require("plugins.plugins_config.fm")

