vim.g.mapleader = ","
vim.keymap.set('n', '<leader>w', ':w<cr>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>1q', ':q!<cr>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>q', ':lua require("keybindings.modules.close_buffer").close_buffer()<CR>', { noremap = true, silent = true  })
vim.keymap.set('n', '<leader><cr>', ':nohlsearch<cr>', {})
vim.api.nvim_set_keymap('n', ';;', 'A;<ESC>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>vmd', ':MarkdownPreview<cr>', {})
vim.keymap.set('n', '<leader>cpf', ':CocCommand php-cs-fixer.fix<cr>', {})
vim.keymap.set('n', '<leader>cfr', ':CocCommand prettier.formatFile<cr>', {})
vim.keymap.set('n', '<leader>o', 'o<ESC>', {})
vim.keymap.set('n', '<leader>O', 'O<ESC>', {})
